### ISSUE TITLE
bone location weird

### ISSUE THREAD

**Issue by star19990** [girlgg/IWToUE#11]
hi im trying to import the doom eternal converted semodel/seanim

when importing into unreal, the bone position is deformed
could you please check this issue?

![blender](https://github.com/girlgg/SeImporter/assets/27559314/77774aac-8999-4ffc-97d9-2b20c1f14b59)
blender (It should look like this)

![unreal adsolute](https://github.com/girlgg/SeImporter/assets/27559314/1a2d9c19-11e1-448d-93e7-6f2fc463f929)
unreal ani type adsolute

![unreal delta](https://github.com/girlgg/SeImporter/assets/27559314/02a66496-8a6b-4ae8-9917-056c2043e64a)
unreal ani type delta

**Comment by girlgg** [comment]
Please provide the .semodel file for me to check the issue. You can use Baidu Pan or Google Drive.

**Comment by star19990** [comment]
https://drive.google.com/file/d/1XPl8Ess440_0L62nVsZ9rv9mYHaDbtg0/view?usp=sharing
here is
semodel and seanim

**Comment by girlgg** [comment]
Due to numerous issues with the plugin when importing skeletal mesh assets, you can export them as FBX using software like Blender and then import them. You can import materials by this plugin.

**Comment by star19990** [comment]
I know how to extract fbx from that tool, but it takes a long time because there are a lot of SEANIM files

**Comment by girlgg** [comment]
Do not use absolute animation, use relative animation.
